[package]
name = "bmbp_rdbc_plugin"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "plugin"
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
